### ISSUE TITLE
Installs on MacOSX despite being linux specific

### ISSUE THREAD

**Issue by jmgurney** [rbarrois/aionotify#10]
```
(p) nmac,ttys017,/tmp/wo,505$python
Python 3.7.5 (default, Oct 18 2019, 23:59:39) 
[Clang 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import aionotify
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/wo/p/lib/python3.7/site-packages/aionotify/__init__.py", line 5, in <module>
    from .base import Watcher
  File "/private/tmp/wo/p/lib/python3.7/site-packages/aionotify/base.py", line 15, in <module>
    _libc = ctypes.cdll.LoadLibrary('libc.so.6')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libc.so.6, 6): image not found
```

**Comment by rbarrois** [comment]
Indeed. However, I haven't been able to find a definitive source listing the possible values for the `platform_*` fields for `setup.py` (A couple of examples are available here: https://www.python.org/dev/peps/pep-0508/#environment-markers).

If you can find the relevant spec, I'll be happy to update the packaging accordingly!

**Comment by hoefling** [comment]
You can't restrict platform in setup keywords, but you can generate platform-specific wheels via e.g. `python setup.py bdist_wheel --plat-name=manylinux1_x86_64` and exit early in the setup script if `sys.platform` doesn't match (when installing from source dists).
