### ISSUE TITLE
`Watcher.setup(loop=None)` raises `AttributeError`

### ISSUE THREAD

**Issue by Skinner927** [rbarrois/aionotify#24]
Using `aionotify==0.3.0`.

Calling `watcher.setup()` without a `loop` will pass `loop=None` to `UnixFileDescriptorTransport`

```python
import aionotify
import asyncio

watcher = aionotify.Watcher()
asyncio.run(watcher.setup())
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/user/tt/venv/lib/python3.10/site-packages/aionotify/base.py", line 91, in setup
    self._stream, self._transport = await aioutils.stream_from_fd(self._fd, loop)
  File "/home/user/tt/venv/lib/python3.10/site-packages/aionotify/aioutils.py", line 128, in stream_from_fd
    transport = UnixFileDescriptorTransport(
  File "/home/user/tt/venv/lib/python3.10/site-packages/aionotify/aioutils.py", line 26, in __init__
    self._loop.call_soon(self._protocol.connection_made, self)
AttributeError: 'NoneType' object has no attribute 'call_soon'
```

The bug is in `base.py`'s `Watcher.setup()` method.

```python
    async def setup(self, loop=None):
        """Start the watcher, registering new watches if any."""
        self._loop = loop or asyncio.get_running_loop()

        self._fd = LibC.inotify_init()
        for alias, (path, flags) in self.requests.items():
            self._setup_watch(alias, path, flags)

        # We pass ownership of the fd to the transport; it will close it.
        self._stream, self._transport = await aioutils.stream_from_fd(self._fd, loop)
```

The last line of the function is the problem. `loop` is being passed instead of the resolved `self._loop`.

```python
self._stream, self._transport = await aioutils.stream_from_fd(self._fd, loop)
```

should be 

```python
self._stream, self._transport = await aioutils.stream_from_fd(self._fd, self._loop)
```

This was not caught in automated testing because `loop` is always passed.

**Comment by Skinner927** [comment]
Current workaround is to always pass `loop` to `Watcher.setup()`

```python
await watcher.setup(loop=asyncio.get_running_loop())
```

**Comment by rbarrois** [comment]
Thanks for the report! This has been fixed, and the fix released.
